#This is a small configuration file for configuring OpenStack
#Set passwords for all OpenStack services, databases

# Configuration of all passwords

ADMIN_PASSWORD=
SERVICE_PASSWORD=
RABBITMQ_PASSWORD=
DATABASE_PASSWORD=
DEMO_PASSWORD=

#Network Configuration
#Enter the IP address of your controller node where all OpenStack services will be installed

HOST_IP=
HOST_IP_CIDR=

#Here you need to enter all the values for the public network, such as Allocation Pool, Gateway and DNS
#It is recommended to enter a larger IP address as Range Start to HOST_IP

PUBLIC_SUBNET_CIDR=
PUBLIC_SUBNET_RANGE_START=
PUBLIC_SUBNET_RANGE_END=
PUBLIC_SUBNET_GATEWAY=
PUBLIC_SUBNET_DNS_SERVERS=

#Specifies the physical interface that will be used for public network external bridge
PUBLIC_BRIDGE_INTERFACE=

PUBLIC_BRIDGE=br-ex
INTERNAL_BRIDGE=br-int
TENANT_NETWORK_TYPE=flat

#Choose whether to install the Block Storage service (Cinder) (Yes or No)
INSTALL_CINDER=no

# File-based backend for testing
CINDER_VOLUME_LVM_IMAGE_FILE_PATH=/var/lib/cinder/images/cinder-volumes.img

# Size of the file-based LVM image for Cinder volumes (in GB)
# NOTE: This does NOT need to match the size of the physical disk
#       Only ensure that there is enough free space on the filesystem
CINDER_VOLUME_LVM_IMAGE_SIZE_IN_GB=10 #

#Set the type of Hypervisor where the instances will run, KVM is the default
NOVA_COMPUTE_VIRT_TYPE=kvm

#Specifies the OpenStack release to install, the default is Caracal
OPENSTACK_RELEASE=caracal
